name: task_manager_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  bottom_sheet: 4.0.1
  cached_network_image: 3.3.1
  cloud_firestore: 4.14.0
  connectivity_plus: 5.0.2
  cupertino_icons: ^1.0.2
  device_preview: 1.1.0
  file_picker: 8.0.0+1
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_messaging: 14.7.9
  firebase_storage: 11.5.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.10+1
  get: 4.6.6
  intl: 0.18.1
  intl_utils: 2.8.7
  shared_preferences: 2.2.2
  shimmer: 3.0.0

dev_dependencies:
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo_app.jpg"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        
flutter_intl:
  enabled: true
  main_locale: vi
